apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the-weather
  namespace: the-weather
spec:
  defaultBackend:
    service:
      name: the-weather-svc
      port:
        number: 80
  ingressClassName: tailscale
  tls:
  - hosts:
    - the-weather
