apiVersion: apps/v1
kind: Deployment
metadata:
  name: field-theories
  namespace: field-theories
spec:
  replicas: 1
  selector:
    matchLabels:
      app: field-theories
  template:
    metadata:
      labels:
        app: field-theories
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/funnel: "true"
    spec:
      containers:
      - name: field-theories
        image: ghcr.io/t-eckert/field-theories:20251128-2006-sha-fe3d065 # {"$imagepolicy": "field-theories:field-theories"}
        ports:
        - containerPort: 4321
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
