apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
  labels:
    app: paperless
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: paperless
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-external
  namespace: paperless
  annotations:
    tailscale.com/hostname: "paperless"
  labels:
    app: paperless
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: paperless