apiVersion: v1
kind: Service
metadata:
  name: atuin
  namespace: atuin
  labels:
    app: atuin
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: atuin
---
apiVersion: v1
kind: Service
metadata:
  name: atuin-external
  namespace: atuin
  annotations:
    tailscale.com/hostname: "atuin-homelab"
  labels:
    app: atuin
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: atuin
