apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fave
  namespace: fave
spec:
  defaultBackend:
    service:
      name: fave-svc
      port:
        number: 80
  ingressClassName: tailscale
  tls:
  - hosts:
    - fave
